// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Chronicles.Web.Controllers {
    [CompilerGenerated]
    public partial class ArchivesController {
        protected ArchivesController(Dummy d) { }

        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = (IT4MVCActionResult)result;
            return RedirectToRoute(callInfo.RouteValues);
        }

        [NonAction]
        public System.Web.Mvc.ActionResult ViewPost() {
            return new T4MVC_ActionResult(Area, Name, Actions.ViewPost);
        }

        public readonly string Area = "";
        public readonly string Name = "Archives";

        static readonly ActionNames s_actions = new ActionNames();
        public ActionNames Actions { get { return s_actions; } }
        public class ActionNames {
            public readonly string ViewPost = "ViewPost";
        }


        static readonly ViewNames s_views = new ViewNames();
        public ViewNames Views { get { return s_views; } }
        public class ViewNames {
            public readonly string ViewPost = "~/Views/Archives/ViewPost.aspx";
        }
    }

    [CompilerGenerated]
    public class T4MVC_ArchivesController: Chronicles.Web.Controllers.ArchivesController {
        public T4MVC_ArchivesController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult ViewPost(int year, int month, int day, int id, string title) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.ViewPost);
            callInfo.RouteValues.Add("year", year);
            callInfo.RouteValues.Add("month", month);
            callInfo.RouteValues.Add("day", day);
            callInfo.RouteValues.Add("id", id);
            callInfo.RouteValues.Add("title", title);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
