// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC {
    [CompilerGenerated]
    public class SharedController {

        static readonly ViewNames s_views = new ViewNames();
        public ViewNames Views { get { return s_views; } }
        public class ViewNames {
            public readonly string Error = "~/Views/Shared/Error.aspx";
            static readonly _DisplayTemplates s_DisplayTemplates = new _DisplayTemplates();
            public _DisplayTemplates DisplayTemplates { get { return s_DisplayTemplates; } }
            public partial class _DisplayTemplates{
                public readonly string CommentDetails = "~/Views/Shared/DisplayTemplates/CommentDetails.ascx";
                public readonly string PostDetails = "~/Views/Shared/DisplayTemplates/PostDetails.ascx";
                public readonly string PostSummary = "~/Views/Shared/DisplayTemplates/PostSummary.ascx";
                public readonly string Tag = "~/Views/Shared/DisplayTemplates/Tag.ascx";
            }
            static readonly _PartialViews s_PartialViews = new _PartialViews();
            public _PartialViews PartialViews { get { return s_PartialViews; } }
            public partial class _PartialViews{
                public readonly string QuickLinksPartial = "~/Views/Shared/PartialViews/QuickLinksPartial.ascx";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591
